/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as peopleEmployeesRouteImport } from './routes/(people)/employees'
import { Route as organiaztionCreateOrganizationRouteImport } from './routes/(organiaztion)/create-organization'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const peopleEmployeesRoute = peopleEmployeesRouteImport.update({
  id: '/(people)/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const organiaztionCreateOrganizationRoute =
  organiaztionCreateOrganizationRouteImport.update({
    id: '/(organiaztion)/create-organization',
    path: '/create-organization',
    getParentRoute: () => rootRouteImport,
  } as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/create-organization': typeof organiaztionCreateOrganizationRoute
  '/employees': typeof peopleEmployeesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/create-organization': typeof organiaztionCreateOrganizationRoute
  '/employees': typeof peopleEmployeesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(organiaztion)/create-organization': typeof organiaztionCreateOrganizationRoute
  '/(people)/employees': typeof peopleEmployeesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/create-organization' | '/employees'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/create-organization' | '/employees'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(organiaztion)/create-organization'
    | '/(people)/employees'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  organiaztionCreateOrganizationRoute: typeof organiaztionCreateOrganizationRoute
  peopleEmployeesRoute: typeof peopleEmployeesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(people)/employees': {
      id: '/(people)/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof peopleEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(organiaztion)/create-organization': {
      id: '/(organiaztion)/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof organiaztionCreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  organiaztionCreateOrganizationRoute: organiaztionCreateOrganizationRoute,
  peopleEmployeesRoute: peopleEmployeesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
