/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as organizationGettingStartedRouteImport } from './routes/(organization)/getting-started'
import { Route as organizationCreateOrganizationRouteImport } from './routes/(organization)/create-organization'
import { Route as organizationAcceptInvitationRouteImport } from './routes/(organization)/accept-invitation'
import { Route as companyVisitorsRouteImport } from './routes/(company)/visitors'
import { Route as companySchedulesRouteImport } from './routes/(company)/schedules'
import { Route as companyLocationsRouteImport } from './routes/(company)/locations'
import { Route as companyAttendanceRouteImport } from './routes/(company)/attendance'
import { Route as companyAnnouncementsRouteImport } from './routes/(company)/announcements'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ProtectedpeopleEmployeesRouteImport } from './routes/_protected/(people)/employees'
import { Route as ProtectedcompanySchedulesRouteImport } from './routes/_protected/(company)/schedules'
import { Route as ProtectedcompanyPermissionsRouteImport } from './routes/_protected/(company)/permissions'
import { Route as ProtectedcompanyLocationsRouteImport } from './routes/_protected/(company)/locations'
import { Route as ProtectedcompanyAttendanceRouteImport } from './routes/_protected/(company)/attendance'
import { Route as ProtectedcompanyAnnouncementsRouteImport } from './routes/_protected/(company)/announcements'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const organizationGettingStartedRoute =
  organizationGettingStartedRouteImport.update({
    id: '/(organization)/getting-started',
    path: '/getting-started',
    getParentRoute: () => rootRouteImport,
  } as any)
const organizationCreateOrganizationRoute =
  organizationCreateOrganizationRouteImport.update({
    id: '/(organization)/create-organization',
    path: '/create-organization',
    getParentRoute: () => rootRouteImport,
  } as any)
const organizationAcceptInvitationRoute =
  organizationAcceptInvitationRouteImport.update({
    id: '/(organization)/accept-invitation',
    path: '/accept-invitation',
    getParentRoute: () => rootRouteImport,
  } as any)
const companyVisitorsRoute = companyVisitorsRouteImport.update({
  id: '/(company)/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const companySchedulesRoute = companySchedulesRouteImport.update({
  id: '/(company)/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const companyLocationsRoute = companyLocationsRouteImport.update({
  id: '/(company)/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const companyAttendanceRoute = companyAttendanceRouteImport.update({
  id: '/(company)/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const companyAnnouncementsRoute = companyAnnouncementsRouteImport.update({
  id: '/(company)/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedpeopleEmployeesRoute =
  ProtectedpeopleEmployeesRouteImport.update({
    id: '/(people)/employees',
    path: '/employees',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedcompanySchedulesRoute =
  ProtectedcompanySchedulesRouteImport.update({
    id: '/(company)/schedules',
    path: '/schedules',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedcompanyPermissionsRoute =
  ProtectedcompanyPermissionsRouteImport.update({
    id: '/(company)/permissions',
    path: '/permissions',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedcompanyLocationsRoute =
  ProtectedcompanyLocationsRouteImport.update({
    id: '/(company)/locations',
    path: '/locations',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedcompanyAttendanceRoute =
  ProtectedcompanyAttendanceRouteImport.update({
    id: '/(company)/attendance',
    path: '/attendance',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedcompanyAnnouncementsRoute =
  ProtectedcompanyAnnouncementsRouteImport.update({
    id: '/(company)/announcements',
    path: '/announcements',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/announcements': typeof companyAnnouncementsRoute
  '/attendance': typeof companyAttendanceRoute
  '/locations': typeof companyLocationsRoute
  '/schedules': typeof companySchedulesRoute
  '/visitors': typeof companyVisitorsRoute
  '/accept-invitation': typeof organizationAcceptInvitationRoute
  '/create-organization': typeof organizationCreateOrganizationRoute
  '/getting-started': typeof organizationGettingStartedRoute
  '/': typeof ProtectedIndexRoute
  '/announcements': typeof ProtectedcompanyAnnouncementsRoute
  '/attendance': typeof ProtectedcompanyAttendanceRoute
  '/locations': typeof ProtectedcompanyLocationsRoute
  '/permissions': typeof ProtectedcompanyPermissionsRoute
  '/schedules': typeof ProtectedcompanySchedulesRoute
  '/employees': typeof ProtectedpeopleEmployeesRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/announcements': typeof companyAnnouncementsRoute
  '/attendance': typeof companyAttendanceRoute
  '/locations': typeof companyLocationsRoute
  '/schedules': typeof companySchedulesRoute
  '/visitors': typeof companyVisitorsRoute
  '/accept-invitation': typeof organizationAcceptInvitationRoute
  '/create-organization': typeof organizationCreateOrganizationRoute
  '/getting-started': typeof organizationGettingStartedRoute
  '/': typeof ProtectedIndexRoute
  '/announcements': typeof ProtectedcompanyAnnouncementsRoute
  '/attendance': typeof ProtectedcompanyAttendanceRoute
  '/locations': typeof ProtectedcompanyLocationsRoute
  '/permissions': typeof ProtectedcompanyPermissionsRoute
  '/schedules': typeof ProtectedcompanySchedulesRoute
  '/employees': typeof ProtectedpeopleEmployeesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(company)/announcements': typeof companyAnnouncementsRoute
  '/(company)/attendance': typeof companyAttendanceRoute
  '/(company)/locations': typeof companyLocationsRoute
  '/(company)/schedules': typeof companySchedulesRoute
  '/(company)/visitors': typeof companyVisitorsRoute
  '/(organization)/accept-invitation': typeof organizationAcceptInvitationRoute
  '/(organization)/create-organization': typeof organizationCreateOrganizationRoute
  '/(organization)/getting-started': typeof organizationGettingStartedRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/(company)/announcements': typeof ProtectedcompanyAnnouncementsRoute
  '/_protected/(company)/attendance': typeof ProtectedcompanyAttendanceRoute
  '/_protected/(company)/locations': typeof ProtectedcompanyLocationsRoute
  '/_protected/(company)/permissions': typeof ProtectedcompanyPermissionsRoute
  '/_protected/(company)/schedules': typeof ProtectedcompanySchedulesRoute
  '/_protected/(people)/employees': typeof ProtectedpeopleEmployeesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/accept-invitation'
    | '/create-organization'
    | '/getting-started'
    | '/'
    | '/announcements'
    | '/attendance'
    | '/locations'
    | '/permissions'
    | '/schedules'
    | '/visitors'
    | '/accept-invitation'
    | '/create-organization'
    | '/getting-started'
    | '/settings'
    | '/employees'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/accept-invitation'
    | '/create-organization'
    | '/getting-started'
    | '/'
    | '/announcements'
    | '/attendance'
    | '/locations'
    | '/permissions'
    | '/schedules'
    | '/visitors'
    | '/accept-invitation'
    | '/create-organization'
    | '/getting-started'
    | '/settings'
    | '/employees'
  id:
    | '__root__'
    | '/_protected'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(company)/announcements'
    | '/(company)/attendance'
    | '/(company)/locations'
    | '/(company)/schedules'
    | '/(company)/visitors'
    | '/(organization)/accept-invitation'
    | '/(organization)/create-organization'
    | '/(organization)/getting-started'
    | '/_protected/'
    | '/_protected/(company)/announcements'
    | '/_protected/(company)/attendance'
    | '/_protected/(company)/locations'
    | '/_protected/(company)/permissions'
    | '/_protected/(company)/schedules'
    | '/_protected/(people)/employees'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  companyAnnouncementsRoute: typeof companyAnnouncementsRoute
  companyAttendanceRoute: typeof companyAttendanceRoute
  companyLocationsRoute: typeof companyLocationsRoute
  companySchedulesRoute: typeof companySchedulesRoute
  companyVisitorsRoute: typeof companyVisitorsRoute
  organizationAcceptInvitationRoute: typeof organizationAcceptInvitationRoute
  organizationCreateOrganizationRoute: typeof organizationCreateOrganizationRoute
  organizationGettingStartedRoute: typeof organizationGettingStartedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/(organization)/getting-started': {
      id: '/(organization)/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof organizationGettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(organization)/create-organization': {
      id: '/(organization)/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof organizationCreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(organization)/accept-invitation': {
      id: '/(organization)/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof organizationAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(company)/visitors': {
      id: '/(company)/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof companyVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(company)/schedules': {
      id: '/(company)/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof companySchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(company)/locations': {
      id: '/(company)/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof companyLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(company)/attendance': {
      id: '/(company)/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof companyAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(company)/announcements': {
      id: '/(company)/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof companyAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/(people)/employees': {
      id: '/_protected/(people)/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof ProtectedpeopleEmployeesRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/(company)/schedules': {
      id: '/_protected/(company)/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof ProtectedcompanySchedulesRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/(company)/permissions': {
      id: '/_protected/(company)/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof ProtectedcompanyPermissionsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/(company)/locations': {
      id: '/_protected/(company)/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof ProtectedcompanyLocationsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/(company)/attendance': {
      id: '/_protected/(company)/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof ProtectedcompanyAttendanceRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/(company)/announcements': {
      id: '/_protected/(company)/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof ProtectedcompanyAnnouncementsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedcompanyAnnouncementsRoute: typeof ProtectedcompanyAnnouncementsRoute
  ProtectedcompanyAttendanceRoute: typeof ProtectedcompanyAttendanceRoute
  ProtectedcompanyLocationsRoute: typeof ProtectedcompanyLocationsRoute
  ProtectedcompanyPermissionsRoute: typeof ProtectedcompanyPermissionsRoute
  ProtectedcompanySchedulesRoute: typeof ProtectedcompanySchedulesRoute
  ProtectedpeopleEmployeesRoute: typeof ProtectedpeopleEmployeesRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedcompanyAnnouncementsRoute: ProtectedcompanyAnnouncementsRoute,
  ProtectedcompanyAttendanceRoute: ProtectedcompanyAttendanceRoute,
  ProtectedcompanyLocationsRoute: ProtectedcompanyLocationsRoute,
  ProtectedcompanyPermissionsRoute: ProtectedcompanyPermissionsRoute,
  ProtectedcompanySchedulesRoute: ProtectedcompanySchedulesRoute,
  ProtectedpeopleEmployeesRoute: ProtectedpeopleEmployeesRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  companyAnnouncementsRoute: companyAnnouncementsRoute,
  companyAttendanceRoute: companyAttendanceRoute,
  companyLocationsRoute: companyLocationsRoute,
  companySchedulesRoute: companySchedulesRoute,
  companyVisitorsRoute: companyVisitorsRoute,
  organizationAcceptInvitationRoute: organizationAcceptInvitationRoute,
  organizationCreateOrganizationRoute: organizationCreateOrganizationRoute,
  organizationGettingStartedRoute: organizationGettingStartedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
