/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as peopleEmployeesRouteImport } from './routes/(people)/employees'
import { Route as organizationSettingsRouteImport } from './routes/(organization)/settings'
import { Route as organizationGettingStartedRouteImport } from './routes/(organization)/getting-started'
import { Route as organizationCreateOrganizationRouteImport } from './routes/(organization)/create-organization'
import { Route as organizationAcceptInvitationRouteImport } from './routes/(organization)/accept-invitation'
import { Route as companySchedulesRouteImport } from './routes/(company)/schedules'
import { Route as companyPermissionsRouteImport } from './routes/(company)/permissions'
import { Route as companyLocationsRouteImport } from './routes/(company)/locations'
import { Route as companyAttendanceRouteImport } from './routes/(company)/attendance'
import { Route as companyAnnouncementsRouteImport } from './routes/(company)/announcements'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const peopleEmployeesRoute = peopleEmployeesRouteImport.update({
  id: '/(people)/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const organizationSettingsRoute = organizationSettingsRouteImport.update({
  id: '/(organization)/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const organizationGettingStartedRoute =
  organizationGettingStartedRouteImport.update({
    id: '/(organization)/getting-started',
    path: '/getting-started',
    getParentRoute: () => rootRouteImport,
  } as any)
const organizationCreateOrganizationRoute =
  organizationCreateOrganizationRouteImport.update({
    id: '/(organization)/create-organization',
    path: '/create-organization',
    getParentRoute: () => rootRouteImport,
  } as any)
const organizationAcceptInvitationRoute =
  organizationAcceptInvitationRouteImport.update({
    id: '/(organization)/accept-invitation',
    path: '/accept-invitation',
    getParentRoute: () => rootRouteImport,
  } as any)
const companySchedulesRoute = companySchedulesRouteImport.update({
  id: '/(company)/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const companyPermissionsRoute = companyPermissionsRouteImport.update({
  id: '/(company)/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const companyLocationsRoute = companyLocationsRouteImport.update({
  id: '/(company)/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const companyAttendanceRoute = companyAttendanceRouteImport.update({
  id: '/(company)/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const companyAnnouncementsRoute = companyAnnouncementsRouteImport.update({
  id: '/(company)/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/announcements': typeof companyAnnouncementsRoute
  '/attendance': typeof companyAttendanceRoute
  '/locations': typeof companyLocationsRoute
  '/permissions': typeof companyPermissionsRoute
  '/schedules': typeof companySchedulesRoute
  '/accept-invitation': typeof organizationAcceptInvitationRoute
  '/create-organization': typeof organizationCreateOrganizationRoute
  '/getting-started': typeof organizationGettingStartedRoute
  '/settings': typeof organizationSettingsRoute
  '/employees': typeof peopleEmployeesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/announcements': typeof companyAnnouncementsRoute
  '/attendance': typeof companyAttendanceRoute
  '/locations': typeof companyLocationsRoute
  '/permissions': typeof companyPermissionsRoute
  '/schedules': typeof companySchedulesRoute
  '/accept-invitation': typeof organizationAcceptInvitationRoute
  '/create-organization': typeof organizationCreateOrganizationRoute
  '/getting-started': typeof organizationGettingStartedRoute
  '/settings': typeof organizationSettingsRoute
  '/employees': typeof peopleEmployeesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(company)/announcements': typeof companyAnnouncementsRoute
  '/(company)/attendance': typeof companyAttendanceRoute
  '/(company)/locations': typeof companyLocationsRoute
  '/(company)/permissions': typeof companyPermissionsRoute
  '/(company)/schedules': typeof companySchedulesRoute
  '/(organization)/accept-invitation': typeof organizationAcceptInvitationRoute
  '/(organization)/create-organization': typeof organizationCreateOrganizationRoute
  '/(organization)/getting-started': typeof organizationGettingStartedRoute
  '/(organization)/settings': typeof organizationSettingsRoute
  '/(people)/employees': typeof peopleEmployeesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/announcements'
    | '/attendance'
    | '/locations'
    | '/permissions'
    | '/schedules'
    | '/accept-invitation'
    | '/create-organization'
    | '/getting-started'
    | '/settings'
    | '/employees'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/announcements'
    | '/attendance'
    | '/locations'
    | '/permissions'
    | '/schedules'
    | '/accept-invitation'
    | '/create-organization'
    | '/getting-started'
    | '/settings'
    | '/employees'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(company)/announcements'
    | '/(company)/attendance'
    | '/(company)/locations'
    | '/(company)/permissions'
    | '/(company)/schedules'
    | '/(organization)/accept-invitation'
    | '/(organization)/create-organization'
    | '/(organization)/getting-started'
    | '/(organization)/settings'
    | '/(people)/employees'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  companyAnnouncementsRoute: typeof companyAnnouncementsRoute
  companyAttendanceRoute: typeof companyAttendanceRoute
  companyLocationsRoute: typeof companyLocationsRoute
  companyPermissionsRoute: typeof companyPermissionsRoute
  companySchedulesRoute: typeof companySchedulesRoute
  organizationAcceptInvitationRoute: typeof organizationAcceptInvitationRoute
  organizationCreateOrganizationRoute: typeof organizationCreateOrganizationRoute
  organizationGettingStartedRoute: typeof organizationGettingStartedRoute
  organizationSettingsRoute: typeof organizationSettingsRoute
  peopleEmployeesRoute: typeof peopleEmployeesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(people)/employees': {
      id: '/(people)/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof peopleEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(organization)/settings': {
      id: '/(organization)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof organizationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(organization)/getting-started': {
      id: '/(organization)/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof organizationGettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(organization)/create-organization': {
      id: '/(organization)/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof organizationCreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(organization)/accept-invitation': {
      id: '/(organization)/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof organizationAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(company)/schedules': {
      id: '/(company)/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof companySchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(company)/permissions': {
      id: '/(company)/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof companyPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(company)/locations': {
      id: '/(company)/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof companyLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(company)/attendance': {
      id: '/(company)/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof companyAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(company)/announcements': {
      id: '/(company)/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof companyAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  companyAnnouncementsRoute: companyAnnouncementsRoute,
  companyAttendanceRoute: companyAttendanceRoute,
  companyLocationsRoute: companyLocationsRoute,
  companyPermissionsRoute: companyPermissionsRoute,
  companySchedulesRoute: companySchedulesRoute,
  organizationAcceptInvitationRoute: organizationAcceptInvitationRoute,
  organizationCreateOrganizationRoute: organizationCreateOrganizationRoute,
  organizationGettingStartedRoute: organizationGettingStartedRoute,
  organizationSettingsRoute: organizationSettingsRoute,
  peopleEmployeesRoute: peopleEmployeesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
